server:
  port: 80
  servlet:
    context-path:

spring:
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root


mybatis-plus:
  type-aliases-package: com.jt.pojo
  mapper-locations:
    classpath: /mapper/*/*.xml
  configuration:
    map-underscore-to-camel-case: true
#check-config-location: true
logging:
  level:
    com.jt: debug
